Map generation
Elderado-City-of-Old/full-bringup pull request #2
Opened 2020-03-05 19:47 UTC by Redfirebird22

Created oro_calibrate package to easily build map using gmapping and teleop nodes. Then use save.sh script to save map in oro_calibrate directory.

2020-03-05 22:24 UTC, ell0ry requested changes
Awesome job Ant! Just a few things to clean things up before merging this. Mostly just nits and comments.

2020-03-05 22:24 UTC, ell0ry commented on oro_calibrate/package.xml
> +  <maintainer email="elderado@todo.todo">elderado</maintainer>
@Redfirebird22 Could you change this to have your email>

2020-03-05 22:24 UTC, ell0ry commented on oro_calibrate/package.xml
> +  <!-- <author email="jane.doe@example.com">Jane Doe</author> -->
Same here, please add yourself as the author!

2020-03-05 22:24 UTC, ell0ry commented on oro_gazebo/launch/oro_house.launch
> +  <arg name="model" default="waffle_pi" doc="model type [burger, waffle, waffle_pi]"/>
Could you add a todo comment here and at all <arg name="model"... lines so we have a papertrail of the intent to remove this?

2020-03-05 22:24 UTC, ell0ry commented on oro_navigation/launch/oro_navigation.launch
> +  <arg name="move_forward_only" default="true"/>
Could you revert this? We want this argument to be false

2020-03-05 22:24 UTC, ell0ry commented on oro_calibrate/launch/oro_calibrate_build.launch
> +	<arg name="model" default="waffle_pi" doc="model type [burger, waffle, waffle_pi]"/>
Same with comment in later launch files, could you add a todo comment here?

2020-03-05 22:24 UTC, ell0ry commented on oro_gazebo/launch/oro_world.launch
> +  <arg name="model" default="waffle_pi" doc="model type [burger, waffle, waffle_pi]"/>
Same as previous comment.

2020-03-05 22:24 UTC, ell0ry commented on oro_slam/config/frontier_exploration.yaml
> +  #explore_clear_space: false
Could you revert this to the default if we're not using explore_boundary?

2020-03-05 22:24 UTC, ell0ry commented on oro_slam/launch/oro_frontier_exploration.launch
> +  <arg name="model" default="waffle_pi" doc="model type [burger, waffle, waffle_pi]"/>
Same as previous comment, todo here please.

2020-03-05 22:24 UTC, ell0ry commented on oro_slam/launch/oro_slam.launch
> +  <arg name="model" default="waffle_pi" doc="model type [burger, waffle, waffle_pi]"/>
Same as previous comment, todo here please.

2020-03-06 04:27 UTC, Redfirebird22 commented
Okay I have gone through and added TODO comments to launch files related to oro_calibrate. I also resolved the other comments. Let me know if there are any other specific places you want me to add TODO comments or anything else you would like me to take care of. Otherwise, I will go ahead and merge.

2020-03-08 23:33 UTC, ell0ry approved these changes

2020-03-08 23:34 UTC, th3rring commented
Awesome job Ant! We'll merge this at the meeting.

2020-03-09 00:50 UTC, merged